project:
  type: website
  output-dir: _site
  preview:
    port: 7777
  post-render: 
    - _marimo_export.py
  render:
    - "*.qmd"
    - "!assignments/"

website:
  title: "MATE 664 Kinetics of Materials (UofA)"
  page-navigation: true
  back-to-top-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: About Course
      - href: syllabus/
        text: Syllabus
      - href: lectures/
        text: Lectures
      - href: scripts.qmd
        text: Interactive Demos
  
  sidebar:
    title: false
    style: "docked"
    search: true
    background: "#f8f9fa"
    id: get-started
    contents:
      - href: index.qmd
        id: guide
      - section: "Syllabus"
        contents:
          - syllabus/index.qmd
      - section: "Lectures"
        contents:
          - lectures/L01/index.qmd
          - lectures/L02/index.qmd
          - lectures/L03/index.qmd
          - lectures/L04/index.qmd
          - lectures/L05/index.qmd
          - lectures/L06/index.qmd
          - lectures/L07/index.qmd
          - lectures/L08/index.qmd
      - section: "Interactive Demos"
        contents:
          - scripts.qmd
          


format:
  revealjs:
    #theme: [simple, reveal-course.scss]
    theme: [default]
    slide-number: true
    chalkboard: false
    preview-links: auto
    transition: none
    navigation-mode: linear
    incremental: false
    scrollable: true
    center: false
    footer: <a href="./index.qmd">MATE 664 · Kinetics of Materials · WS 2026 ↰</a>
    title-slide-attributes:
      data-background-color: "#efefef"
    number-sections: false
    width: 1600
    height: 900
    
  html:
    theme: cosmo
    toc: true
    code-tools: true
    code-fold: true
    code-summary: "Show the code"
